/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
#define uint32_t     unsigned long
#define sint32_t     signed long
#define uint16_t     unsigned int
#define sint16_t     signed int
#define char_t       char
#define uint8_t      unsigned char
#define sint8_t      signed char
#define boolean_t    unsigned char
#define True         1
#define False        0
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
